export const GAME_CONFIG = {
    uno: {
        gameType: 'UNO' as const,
        label: 'UNO',
        icon: '🃏',
        higherIsBetter: true,
        scoreLabel: 'Points',
        description: "À UNO, plus tu marques de points, mieux c’est ! À chaque manche, le gagnant récupère la valeur des cartes restantes des autres joueurs (chiffres = valeur, actions = 20 pts, jokers = 50 pts). Le classement est basé sur le total des points cumulés sur toutes les parties. En 2v2, les points sont partagés entre les coéquipiers.",
    },
    skyjow: {
        gameType: 'SKYJOW' as const,
        label: 'Skyjow',
        icon: '🂠',
        higherIsBetter: false,
        scoreLabel: 'Score moyen',
        description: "À Skyjow, moins de points c’est mieux ! Le classement repose sur le score moyen par partie (somme des cartes restantes). Les colonnes de 3 cartes identiques sont supprimées. Attention : si tu déclenches la fin de manche sans avoir le plus petit score, le tien est doublé.",
    },
    taboo: {
        gameType: 'TABOO' as const,
        label: 'Taboo',
        icon: '🗣️',
        higherIsBetter: true,
        scoreLabel: 'Mots devinés',
        description: "Fais deviner un maximum de mots à ton équipe sans utiliser les mots interdits ! Chaque mot trouvé rapporte 1 point. Le classement correspond au total de mots devinés sur l’ensemble des parties.",
    },
    quiz: {
        gameType: 'QUIZ' as const,
        label: 'Quiz',
        icon: '🎯',
        higherIsBetter: true,
        scoreLabel: 'Score total',
        description: "Teste tes connaissances ! Pour chaque quiz, seul ton meilleur score est conservé. Ton score total correspond à la somme de tes meilleurs résultats sur tous les quiz joués.",
    },
    yahtzee: {
        gameType: 'YAHTZEE' as const,
        label: 'Yahtzee',
        icon: '🎲',
        higherIsBetter: true,
        scoreLabel: 'Score total',
        description: "Accumule un maximum de points en remplissant intelligemment les différentes catégories. Bonus : +35 points si la section haute atteint 63, et +100 pour chaque Yahtzee supplémentaire. Le classement est basé sur le score total cumulé.",
    },
    puissance4: {
        gameType: 'PUISSANCE4' as const,
        label: 'Puissance 4',
        icon: '🔴',
        higherIsBetter: true,
        scoreLabel: 'Victoires',
        description: "Aligne 4 pions avant ton adversaire pour gagner ! Chaque victoire rapporte 1 point. Le classement est basé sur le total de victoires accumulées.",
    },
    'just-one': {
        gameType: 'JUST_ONE' as const,
        label: 'Just One',
        icon: '🔤',
        higherIsBetter: true,
        scoreLabel: 'Score moyen',
        description: "Jeu coopératif : fais deviner un mot mystère avec des indices uniques. Les indices identiques sont annulés ! Le score (sur 13) reflète la performance moyenne de ton équipe.",
    },
    'battleship': {
        gameType: 'BATTLESHIP' as const,
        label: 'Bataille Navale',
        icon: '🚢',
        higherIsBetter: true,
        scoreLabel: 'Victoires',
        description: "Coule la flotte ennemie avant que la tienne ne disparaisse ! Chaque partie gagnée rapporte 1 point. Le classement est basé sur le nombre total de victoires.",
    },
} as const;
